### ISSUE TITLE
Issues running the setup.sh script

### ISSUE THREAD

**Issue by ramakris** [redhat-solution-patterns/redhat-solution-patterns.github.io#1]
**Describe the bug**
I am a Red Hat Employee
So I spun of a OpenShift AI AWS cluster from the demo site  (demo.redhat.com) and logged into the bastion host and ran the script setup.sh

Here are the errors I ran into

WARNING: Discarding https://files.pythonhosted.org/packages/6c/f6/215ba9e8d2587755df363170e3be54892b087bad0a99935fe456f7555255/onnx-1.13.0.tar.gz#sha256=410b39950367857f97b65093681fe2495a2e23d63777a8aceaf96c56a16d166e (from https://pypi.org/simple/onnx/). Command errored out with exit status 1: /home/lab-user/deployment/venv/bin/python3 /home/lab-user/deployment/venv/lib64/python3.6/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmpvab2pair Check the logs for full command output.
  ERROR: Command errored out with exit status 1:
   command: /home/lab-user/deployment/venv/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-xdikwbkp/onnx_5e6c2f4a20ae45668334b8a0fb6248a6/setup.py'"'"'; __file__='"'"'/tmp/pip-install-xdikwbkp/onnx_5e6c2f4a20ae45668334b8a0fb6248a6/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-wcfcedpe
       cwd: /tmp/pip-install-xdikwbkp/onnx_5e6c2f4a20ae45668334b8a0fb6248a6/
  Complete output (6 lines):
  fatal: not a git repository (or any of the parent directories): .git
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-xdikwbkp/onnx_5e6c2f4a20ae45668334b8a0fb6248a6/setup.py", line 81, in <module>
      assert CMAKE, "Could not find cmake executable!"
  AssertionError: Could not find cmake executable!
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/2c/6a/39b0580858589a67c3322aabc2634f158391ffbf98fa410127533e7f1495/onnx-1.12.0.tar.gz#sha256=13b3e77d27523b9dbf4f30dfc9c959455859d5e34e921c44f712d69b8369eff9 (from https://pypi.org/simple/onnx/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Cannot install numpy and numpy==1.23.* because these package versions have conflicting dependencies.
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies

  Run the following:

  # activate python virtual env (bash)
  source venv/bin/activate

  # blastoff w/ jupyter
  jupyter-lab

**Comment by jayachristina** [comment]
Hi
Which pattern are you referring to here please?

**Comment by ramakris** [comment]
This is the one I am following.

https://www.solutionpatterns.io/solution-pattern-predict-stock-price-trend-using-rhoai/solution-pattern-predict-stock-price-trend-using-rhoai/04-workshop.html

--RamaK

**Comment by jayachristina** [comment]
@gmidha1 can you please check this one out? thank you :)

**Comment by gmidha1** [comment]
@ramakris , let us connect over slack. I already pinged you there.
