### ISSUE TITLE
Wrong spelling of Kubernetes, Kuberenetes

### ISSUE THREAD

**Issue by cepr1969** [redhat-solution-patterns/redhat-solution-patterns.github.io#2]
**Solution Pattern**
1. Name of the pattern/URL
2. Section where the bug is found

https://github.com/redhat-solution-patterns/redhat-solution-patterns.github.io/blob/main/content/patterns/solution-pattern-instant-multicloud.md

https://github.com/redhat-solution-patterns/redhat-solution-patterns.github.io/blob/main/content/patterns/solution-pattern-cluster-as-a-service.md

**Describe the bug**

The word "Kuberenetes" is used instead of "Kubernetes"

**To Reproduce**

**Expected behavior**

**Screenshots**

![image](https://github.com/user-attachments/assets/cea9924f-815c-46a7-8625-9d6666c88cd8)

**Additional context**

**Comment by jayachristina** [comment]
Thank you very much for the bug report. Corrected now
